### ISSUE TITLE
加密插件无法加密handsome编辑器里添加的视频

### ISSUE THREAD

**Issue by wnark** [wuxianucw/PartiallyPassword#1]
在handsome的编辑器里添加视频，在视频的首位加上加密标记
![Inked H}_C1037M{CB@X_J43J$V2_LI](https://user-images.githubusercontent.com/24355466/70390116-2539f200-1a03-11ea-970e-a2f03f6e9659.jpg)
保存文章后，标记自动消失，加密失效
![InkedW8E~ G%W6 @XTPPC{V{U972_LI](https://user-images.githubusercontent.com/24355466/70390121-3125b400-1a03-11ea-843b-c094f87c6ea5.jpg)

**Comment by wuxianucw** [comment]
收到，感谢反馈，经确认可能是目前的 filter 钩子优先级过高，正在做调整，请耐心等待，这个版本的插件请尽量避免编辑已经开启加密的文章，可能导致加密部分内容丢失。
