### ISSUE TITLE
最新版typecho release下载最新版插件，文章显示代码，不加密

### ISSUE THREAD

**Issue by a57571735** [wuxianucw/PartiallyPassword#3]
最新版typecho release下载最新版插件，文章显示代码，不加密
插件已正确启用，但是无效

**Comment by a57571735** [comment]
是不是用了其他主题的原因？应该怎么改才行？

**Comment by wuxianucw** [comment]
请确认文章下方“自定义字段”中“是否开启文章部分加密”处于“开启”状态。------------------&nbsp;Original&nbsp;------------------

**Comment by wuxianucw** [comment]
缺少详细信息，无法确定问题，issue 将被 close。
